# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'veesionDpBCfq.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(430, 608)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 50, 201, 251))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.pushButton_connect = QPushButton(self.frame)
        self.pushButton_connect.setObjectName(u"pushButton_connect")
        self.pushButton_connect.setGeometry(QRect(10, 40, 181, 21))
        self.textEdit = QTextEdit(self.frame)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(60, 10, 131, 21))
        self.label_rpi_ip = QLabel(self.frame)
        self.label_rpi_ip.setObjectName(u"label_rpi_ip")
        self.label_rpi_ip.setGeometry(QRect(10, 10, 101, 17))
        self.label_rpi_status = QLabel(self.frame)
        self.label_rpi_status.setObjectName(u"label_rpi_status")
        self.label_rpi_status.setGeometry(QRect(10, 70, 81, 17))
        self.textBrowser_2 = QTextBrowser(self.frame)
        self.textBrowser_2.setObjectName(u"textBrowser_2")
        self.textBrowser_2.setGeometry(QRect(70, 70, 121, 21))
        self.label_cam = QLabel(self.frame)
        self.label_cam.setObjectName(u"label_cam")
        self.label_cam.setGeometry(QRect(10, 100, 71, 17))
        self.label_imu = QLabel(self.frame)
        self.label_imu.setObjectName(u"label_imu")
        self.label_imu.setGeometry(QRect(10, 130, 71, 17))
        self.label_client = QLabel(self.frame)
        self.label_client.setObjectName(u"label_client")
        self.label_client.setGeometry(QRect(10, 160, 71, 17))
        self.label_play = QLabel(self.frame)
        self.label_play.setObjectName(u"label_play")
        self.label_play.setGeometry(QRect(10, 190, 51, 17))
        self.pb_run_cam = QPushButton(self.frame)
        self.pb_run_cam.setObjectName(u"pb_run_cam")
        self.pb_run_cam.setGeometry(QRect(70, 100, 51, 25))
        self.pb_stop_cam = QPushButton(self.frame)
        self.pb_stop_cam.setObjectName(u"pb_stop_cam")
        self.pb_stop_cam.setGeometry(QRect(120, 100, 51, 25))
        self.pb_run_imu = QPushButton(self.frame)
        self.pb_run_imu.setObjectName(u"pb_run_imu")
        self.pb_run_imu.setGeometry(QRect(70, 130, 51, 25))
        self.pb_stop_imu = QPushButton(self.frame)
        self.pb_stop_imu.setObjectName(u"pb_stop_imu")
        self.pb_stop_imu.setGeometry(QRect(120, 130, 51, 25))
        self.pb_run_client = QPushButton(self.frame)
        self.pb_run_client.setObjectName(u"pb_run_client")
        self.pb_run_client.setGeometry(QRect(70, 160, 51, 25))
        self.pb_stop_client = QPushButton(self.frame)
        self.pb_stop_client.setObjectName(u"pb_stop_client")
        self.pb_stop_client.setGeometry(QRect(120, 160, 51, 25))
        self.pb_run_play = QPushButton(self.frame)
        self.pb_run_play.setObjectName(u"pb_run_play")
        self.pb_run_play.setGeometry(QRect(70, 190, 51, 25))
        self.pb_stop_play = QPushButton(self.frame)
        self.pb_stop_play.setObjectName(u"pb_stop_play")
        self.pb_stop_play.setGeometry(QRect(120, 190, 51, 25))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(220, 50, 201, 251))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.label_pc_ip = QLabel(self.frame_2)
        self.label_pc_ip.setObjectName(u"label_pc_ip")
        self.label_pc_ip.setGeometry(QRect(10, 10, 51, 20))
        self.label_pc_status = QLabel(self.frame_2)
        self.label_pc_status.setObjectName(u"label_pc_status")
        self.label_pc_status.setGeometry(QRect(10, 40, 81, 17))
        self.checkBox_points = QCheckBox(self.frame_2)
        self.checkBox_points.setObjectName(u"checkBox_points")
        self.checkBox_points.setGeometry(QRect(120, 70, 81, 23))
        self.checkBox_img = QCheckBox(self.frame_2)
        self.checkBox_img.setObjectName(u"checkBox_img")
        self.checkBox_img.setGeometry(QRect(10, 70, 51, 23))
        self.checkBox_path = QCheckBox(self.frame_2)
        self.checkBox_path.setObjectName(u"checkBox_path")
        self.checkBox_path.setGeometry(QRect(60, 70, 51, 23))
        self.label_server = QLabel(self.frame_2)
        self.label_server.setObjectName(u"label_server")
        self.label_server.setGeometry(QRect(10, 100, 71, 17))
        self.label_gazebo = QLabel(self.frame_2)
        self.label_gazebo.setObjectName(u"label_gazebo")
        self.label_gazebo.setGeometry(QRect(10, 160, 71, 17))
        self.pb_run_server = QPushButton(self.frame_2)
        self.pb_run_server.setObjectName(u"pb_run_server")
        self.pb_run_server.setGeometry(QRect(90, 100, 51, 25))
        self.label_rviz = QLabel(self.frame_2)
        self.label_rviz.setObjectName(u"label_rviz")
        self.label_rviz.setGeometry(QRect(10, 130, 71, 17))
        self.pb_stop_server = QPushButton(self.frame_2)
        self.pb_stop_server.setObjectName(u"pb_stop_server")
        self.pb_stop_server.setGeometry(QRect(140, 100, 51, 25))
        self.pb_run_rviz = QPushButton(self.frame_2)
        self.pb_run_rviz.setObjectName(u"pb_run_rviz")
        self.pb_run_rviz.setGeometry(QRect(90, 130, 51, 25))
        self.pb_stop_rviz = QPushButton(self.frame_2)
        self.pb_stop_rviz.setObjectName(u"pb_stop_rviz")
        self.pb_stop_rviz.setGeometry(QRect(140, 130, 51, 25))
        self.pb_run_gazebo = QPushButton(self.frame_2)
        self.pb_run_gazebo.setObjectName(u"pb_run_gazebo")
        self.pb_run_gazebo.setGeometry(QRect(90, 160, 51, 25))
        self.pb_stop_gazebo = QPushButton(self.frame_2)
        self.pb_stop_gazebo.setObjectName(u"pb_stop_gazebo")
        self.pb_stop_gazebo.setGeometry(QRect(140, 160, 51, 25))
        self.comboBox_worlds = QComboBox(self.frame_2)
        self.comboBox_worlds.addItem("")
        self.comboBox_worlds.addItem("")
        self.comboBox_worlds.addItem("")
        self.comboBox_worlds.setObjectName(u"comboBox_worlds")
        self.comboBox_worlds.setGeometry(QRect(90, 190, 101, 20))
        self.label_worlds = QLabel(self.frame_2)
        self.label_worlds.setObjectName(u"label_worlds")
        self.label_worlds.setGeometry(QRect(10, 190, 67, 17))
        self.textBrowser_3 = QTextBrowser(self.frame_2)
        self.textBrowser_3.setObjectName(u"textBrowser_3")
        self.textBrowser_3.setGeometry(QRect(60, 40, 131, 21))
        self.textEdit_2 = QTextEdit(self.frame_2)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(60, 10, 131, 21))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 310, 411, 251))
        self.tab_algorithm = QWidget()
        self.tab_algorithm.setObjectName(u"tab_algorithm")
        self.textBrowser = QTextBrowser(self.tab_algorithm)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(0, 10, 401, 201))
        self.tabWidget.addTab(self.tab_algorithm, "")
        self.tab_camimu = QWidget()
        self.tab_camimu.setObjectName(u"tab_camimu")
        self.textBrowser_4 = QTextBrowser(self.tab_camimu)
        self.textBrowser_4.setObjectName(u"textBrowser_4")
        self.textBrowser_4.setGeometry(QRect(0, 10, 401, 201))
        self.tabWidget.addTab(self.tab_camimu, "")
        self.tab_comm = QWidget()
        self.tab_comm.setObjectName(u"tab_comm")
        self.textBrowser_5 = QTextBrowser(self.tab_comm)
        self.textBrowser_5.setObjectName(u"textBrowser_5")
        self.textBrowser_5.setGeometry(QRect(0, 10, 401, 201))
        self.tabWidget.addTab(self.tab_comm, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.textBrowser_6 = QTextBrowser(self.tab)
        self.textBrowser_6.setObjectName(u"textBrowser_6")
        self.textBrowser_6.setGeometry(QRect(0, 10, 401, 201))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.textBrowser_7 = QTextBrowser(self.tab_2)
        self.textBrowser_7.setObjectName(u"textBrowser_7")
        self.textBrowser_7.setGeometry(QRect(0, 10, 401, 201))
        self.tabWidget.addTab(self.tab_2, "")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(70, 0, 311, 41))
        font = QFont()
        font.setFamily(u"FreeMono")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 430, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(3)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.pushButton_connect.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label_rpi_ip.setText(QCoreApplication.translate("MainWindow", u"RPI IP :", None))
        self.label_rpi_status.setText(QCoreApplication.translate("MainWindow", u"Status :", None))
        self.label_cam.setText(QCoreApplication.translate("MainWindow", u"Camera:", None))
        self.label_imu.setText(QCoreApplication.translate("MainWindow", u"IMU:", None))
        self.label_client.setText(QCoreApplication.translate("MainWindow", u"Client:", None))
        self.label_play.setText(QCoreApplication.translate("MainWindow", u"Play:", None))
        self.pb_run_cam.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pb_stop_cam.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pb_run_imu.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pb_stop_imu.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pb_run_client.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pb_stop_client.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pb_run_play.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pb_stop_play.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.label_pc_ip.setText(QCoreApplication.translate("MainWindow", u"PC IP :", None))
        self.label_pc_status.setText(QCoreApplication.translate("MainWindow", u"Status :", None))
        self.checkBox_points.setText(QCoreApplication.translate("MainWindow", u"Points", None))
        self.checkBox_img.setText(QCoreApplication.translate("MainWindow", u"Img", None))
        self.checkBox_path.setText(QCoreApplication.translate("MainWindow", u"Path", None))
        self.label_server.setText(QCoreApplication.translate("MainWindow", u"Server:", None))
        self.label_gazebo.setText(QCoreApplication.translate("MainWindow", u"Gazebo:", None))
        self.pb_run_server.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.label_rviz.setText(QCoreApplication.translate("MainWindow", u"Rviz:", None))
        self.pb_stop_server.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pb_run_rviz.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pb_stop_rviz.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pb_run_gazebo.setText(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.pb_stop_gazebo.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.comboBox_worlds.setItemText(0, QCoreApplication.translate("MainWindow", u"Cafe", None))
        self.comboBox_worlds.setItemText(1, QCoreApplication.translate("MainWindow", u"Office", None))
        self.comboBox_worlds.setItemText(2, QCoreApplication.translate("MainWindow", u"Lab", None))

        self.label_worlds.setText(QCoreApplication.translate("MainWindow", u"Worlds:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_algorithm), QCoreApplication.translate("MainWindow", u"Main", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_camimu), QCoreApplication.translate("MainWindow", u"Cam", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_comm), QCoreApplication.translate("MainWindow", u"IMU", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Server", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Client", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"vEEsion VR System", None))
    # retranslateUi


